sudo: false

language: python

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_VERSION=dj17
  - DJANGO_VERSION=dj18
  - DJANGO_VERSION=dj19
  - DJANGO_VERSION=dj110
  - DJANGO_VERSION=djdev

matrix:
  allow_failures:
    - env: DJANGO_VERSION=djdev
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=dj17
  include:
    - python: "2.7"
      env: MODE=flake8
    - python: "3.4"
      env: DJANGO_VERSION=dj17

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
    - pip install -U pip
    - pip install -U wheel virtualenv
    - pip install tox coveralls
    - python setup.py install

after_success:
    - coveralls

script:
    - coverage erase
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION}${MODE}
