# Generated by Django 2.0.13 on 2022-08-31 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_channel_file_failpost_file_forbiddenpost_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionChannel",
            fields=[
                (
                    "channel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.Channel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("main.channel",),
        ),
        migrations.CreateModel(
            name="ProxyChannel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
            },
            bases=("main.channel",),
        ),
    ]
